export const Listing = [
    {
        id: '1',
        image_user: require('../../../assets/img/user.png'),
        image_property: require('../../../assets/img/nava.png'),
        lokasi: "Century 21 BSD City",
        property_name: "Nava Park BSD City",
        peperty_cat: "Rumah",
        property_price: "Rp 6.500.000.000",
        sale_type: "sell",
        property_address: "Jl. Edutown Kav III.1, BSD, Tangerang Selatan",
        k_tidur: "3+1",
        k_mandi: "3+1",
        l_tanah: "300m",
        property_owner: "Henry Scott",
        is_private: false,
        sold: false
    },
    {
        id: '2',
        image_user: require('../../../assets/img/user.png'),
        image_property: require('../../../assets/img/rumah.png'),
        lokasi: "Century 21 BSD City",
        property_name: "Woody Residence Foresta",
        peperty_cat: "Rumah",
        property_price: "Rp 10.000.000/ Bulan",
        sale_type: "rent",
        property_address: "Jl. Edutown Kav III.1, BSD, Tangerang Selatan",
        k_tidur: "4",
        k_mandi: "4",
        l_tanah: "275m",
        property_owner: "Henry Scott",
        is_private: true,
        sold: false
    },
]
export const Favofite = [
    {
        id: '3',
        image_user: require('../../../assets/img/user.png'),
        image_property: require('../../../assets/img/bresidence.png'),
        lokasi: "Century 21 BSD City",
        property_name: "B Residence BSD Signature Lotus …",
        peperty_cat: "Rumah",
        property_price: "Rp 2.500.000.000",
        sale_type: "sell",
        property_address: "Jl. Edutown Kav III.1, BSD, Tangerang Selatan",
        k_tidur: "3+1",
        k_mandi: "2+1",
        l_tanah: "118m",
        property_owner: "Andrea Collins",
        is_private: false,
        sold: false
    },
    {
        id: '4',
        image_user: require('../../../assets/img/user.png'),
        image_property: require('../../../assets/img/branz.png'),
        lokasi: "Century 21 BSD City",
        property_name: "The Branz Apartment BSD City",
        peperty_cat: "Rumah",
        property_price: "Rp 2.250.000.000 / Bulan",
        sale_type: "sell",
        property_address: "Jl. Edutown Kav III.1, BSD, Tangerang Selatan",
        k_tidur: "3+1",
        k_mandi: "2+1",
        l_tanah: "85m",
        property_owner: "Stewat Vale",
        is_private: false,
        sold: false
    },
]
export const Arsip = [
    {
        id: '5',
        image_user: require('../../../assets/img/user.png'),
        image_property: require('../../../assets/img/bresidenceApart.png'),
        lokasi: "Century 21 BSD City",
        property_name: "B Residence BSD Signature Lotus …",
        peperty_cat: "Apartemen",
        property_price: "Rp 4.000.000 / Bulan",
        sale_type: "rent",
        property_address: "Jl. Edutown Kav III.1, BSD, Tangerang Selatan",
        k_tidur: "2",
        k_mandi: "2",
        l_tanah: "50m",
        property_owner: "Henry Scott",
        is_private: true,
        sold: true
    },
    {
        id: '6',
        image_user: require('../../../assets/img/user.png'),
        image_property: require('../../../assets/img/forestaultimo.png'),
        lokasi: "Century 21 BSD City",
        property_name: "B Residence BSD Signature Lotus …",
        peperty_cat: "Rumah",
        property_price: "Rp 2.500.000.000",
        sale_type: "sell",
        property_address: "Jl. Edutown Kav III.1, BSD, Tangerang Selatan",
        k_tidur: "3+1",
        k_mandi: "2+1",
        l_tanah: "118m",
        property_owner: "Henry Scott",
        is_private: false,
        sold: true
    },
]